spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/popcon
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: true
  profiles:
    include: API-KEY